# Generated by Django 5.2.10 on 2026-01-31 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climateconnect_api', '0099_add_context_to_feedback'),
        ('hubs', '0044_auto_20260126_1612'),
        ('location', '0016_auto_20260122_1706'),
        ('organization', '0116_set_default_has_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='has_children',
            field=models.BooleanField(db_index=True, default=False, help_text='Flag indicating if this project has child projects (events).'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['name'], name='org_name_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['-id'], name='org_newest_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['-created_at'], name='org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_draft', 'is_active'], name='project_draft_active_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_draft', 'is_active', '-id'], name='project_newest_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_draft', 'is_active', '-created_at'], name='project_created_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_draft', 'is_active', 'project_type'], name='project_type_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_draft', 'is_active', 'collaborators_welcome'], name='project_collab_idx'),
        ),
    ]
