"""
Django settings for climateconnect_main project.

Generated by 'django-admin startproject' using Django 2.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import ssl
from datetime import timedelta

from dotenv import find_dotenv, load_dotenv

from climateconnect_main.utility.general import get_allowed_hosts
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration
from sentry_sdk.integrations.redis import RedisIntegration
from sentry_sdk.integrations.celery import CeleryIntegration
import django.conf

load_dotenv(find_dotenv(".backend_env"))


env = os.environ.get

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG", "false") == "true"  # needs to gravitate towards False!

ALLOWED_HOSTS = get_allowed_hosts(env("ALLOWED_HOSTS"))


INTERNAL_IPS = [
    # ...
    "127.0.0.1",
    # ...
]


AUTO_VERIFY = True if env("AUTO_VERIFY") in ["True", "true", "TRUE"] else False

# Application definition

CUSTOM_APPS = [
    "climateconnect_api",
    "organization",
    "chat_messages",
    "hubs",
    "location",
    "ideas",
    "climate_match",
]

LIBRARY_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "drf_spectacular",
    "knox",
    "corsheaders",
    "channels",
    "django_filters",
    "django.contrib.gis",
    "django_celery_beat",
]

DEBUG_APPS = ["debug_toolbar"]

DEBUG_TOOLBAR_CONFIG = {
    "SHOW_TOOLBAR_CALLBACK": lambda request: django.conf.settings.DEBUG,
    "SHOW_COLLAPSED": False,  # Default is False
}

SECURITY_MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
]

# Compression middleware - GZip for all browsers
# Note: django-brotli can be added later for ~20% better compression
COMPRESSION_MIDDLEWARE = [
    "django.middleware.gzip.GZipMiddleware",
]

# Performance middleware for sub-500ms FCP
PERFORMANCE_MIDDLEWARE = [
    "climateconnect_main.middleware.performance.ServerTimingMiddleware",
    "climateconnect_main.middleware.performance.CacheControlMiddleware",
    "climateconnect_main.middleware.performance.ETagMiddleware",
    "climateconnect_main.middleware.performance.PreloadHintsMiddleware",
]

DEBUG_MIDDLEWARE = ["debug_toolbar.middleware.DebugToolbarMiddleware"]

NORMAL_MIDDLEWARE = [
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

if env("DEBUG"):
    INSTALLED_APPS = CUSTOM_APPS + LIBRARY_APPS + DEBUG_APPS
    MIDDLEWARE = SECURITY_MIDDLEWARE + COMPRESSION_MIDDLEWARE + PERFORMANCE_MIDDLEWARE + DEBUG_MIDDLEWARE + NORMAL_MIDDLEWARE
else:
    INSTALLED_APPS = CUSTOM_APPS + LIBRARY_APPS
    MIDDLEWARE = SECURITY_MIDDLEWARE + COMPRESSION_MIDDLEWARE + PERFORMANCE_MIDDLEWARE + NORMAL_MIDDLEWARE

CORS_ORIGIN_WHITELIST = [
    "http://localhost:3000",
    "https://frontend-dot-inbound-lexicon-271522.ey.r.appspot.com",
    "https://alpha.climateconnect.earth",
    "https://climateconnect.earth",
    "https://test3425.climateconnect.earth",
    "https://www.climateconnect.earth",
    "https://www.cc-test-domain.com",
    "https://cc-test-domain.com",
    "http://cc-test-domain.com",
    "https://test-climateconnect-frontend.azurewebsites.net",
    "https://climateconnect-frontend-slot2.azurewebsites.net",
    "https://climateconnect-frontend-slot2-b4ege4evbjeeabeb.germanywestcentral-01.azurewebsites.net",
]
APPEND_SLASH = False

ROOT_URLCONF = "climateconnect_main.urls"


TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "climateconnect_main.wsgi.application"


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "NAME": env("DATABASE_NAME"),
        "USER": env("DATABASE_USER"),
        "PASSWORD": env("DATABASE_PASSWORD"),
        "HOST": env("DATABASE_HOST"),
        "PORT": env("DATABASE_PORT", "5432"),
        # Connection pooling for better performance
        "CONN_MAX_AGE": 600,  # Keep connections alive for 10 minutes
        "CONN_HEALTH_CHECKS": True,  # Django 5.x: Check connection health before use
        "OPTIONS": {
            "connect_timeout": 10,
            "options": "-c statement_timeout=30000",  # 30 second query timeout
        },
    }
}

# Use persistent database connections for async performance
if env("ENVIRONMENT") == "production":
    DATABASES["default"]["CONN_MAX_AGE"] = None  # Persistent connections in production

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
# USE_L10N is deprecated in Django 4.0+ and always True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
if env("ENVIRONMENT") not in ("development", "test"):
    # Django 4.2+ uses STORAGES instead of DEFAULT_FILE_STORAGE/STATICFILES_STORAGE
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.azure_storage.AzureStorage",
        },
        "staticfiles": {
            "BACKEND": "storages.backends.azure_storage.AzureStorage",
        },
    }
    AZURE_ACCOUNT_NAME = env("AZURE_ACCOUNT_NAME")
    AZURE_ACCOUNT_KEY = env("AZURE_ACCOUNT_KEY")
    AZURE_CONTAINER = env("AZURE_CONTAINER")
else:
    # Use default local file storage for development/test
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }

STATIC_URL = (
    "/static/"
    if env("ENVIRONMENT") in ("development", "test")
    else "https://"
    + env("AZURE_ACCOUNT_NAME")
    + "."
    + env("AZURE_HOST")
    + "/{}/".format(env("AZURE_CONTAINER"))
)
STATIC_ROOT = (
    env("STATIC_ROOT") if env("ENVIRONMENT") in ("development", "test") else "static/"
)
MEDIA_ROOT = env("MEDIA_ROOT")
MEDIA_URL = "/media/"

REST_KNOX = {"TOKEN_TTL": timedelta(days=120)}
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "knox.auth.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 200,
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    # Performance: Use orjson for faster JSON serialization (up to 10x faster)
    "DEFAULT_RENDERER_CLASSES": [
        "climateconnect_main.renderers.ORJSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
    "DEFAULT_PARSER_CLASSES": [
        "climateconnect_main.parsers.ORJSONParser",
        "rest_framework.parsers.FormParser",
        "rest_framework.parsers.MultiPartParser",
    ],
}

SPECTACULAR_SETTINGS = {
    "TITLE": "ClimateConnect API",
    "DESCRIPTION": "API for Climate Connect platform - connecting climate activists, organizations, and projects to solve the climate crisis",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "SCHEMA_PATH_PREFIX": r"/api/",
}


MJ_APIKEY_PUBLIC = env("MJ_APIKEY_PUBLIC", "")
MJ_APIKEY_PRIVATE = env("MJ_APIKEY_PRIVATE", "")
MAILJET_NEWSLETTER_LIST_ID = env("MAILJET_NEWSLETTER_LIST_ID")
CLIMATE_CONNECT_SUPPORT_EMAIL = env("CLIMATE_CONNECT_SUPPORT_EMAIL", "")

EMAIL_VERIFICATION_TEMPLATE_ID = env("EMAIL_VERIFICATION_TEMPLATE_ID", "")
NEW_EMAIL_VERIFICATION_TEMPLATE_ID = env("NEW_EMAIL_VERIFICATION_TEMPLATE_ID", "")
NEW_EMAIL_VERIFICATION_TEMPLATE_ID_DE = env("NEW_EMAIL_VERIFICATION_TEMPLATE_ID_DE")
EMAIL_VERIFICATION_TEMPLATE_ID_DE = env("EMAIL_VERIFICATION_TEMPLATE_ID_DE")
RESET_PASSWORD_TEMPLATE_ID = env("RESET_PASSWORD_TEMPLATE_ID", "")
RESET_PASSWORD_TEMPLATE_ID_DE = env("RESET_PASSWORD_TEMPLATE_ID_DE")
FEEDBACK_TEMPLATE_ID = env("FEEDBACK_TEMPLATE_ID")
PRIVATE_MESSAGE_TEMPLATE_ID = env("PRIVATE_MESSAGE_TEMPLATE_ID")
PRIVATE_MESSAGE_TEMPLATE_ID_DE = env("PRIVATE_MESSAGE_TEMPLATE_ID_DE")
GROUP_MESSAGE_TEMPLATE_ID = env("GROUP_MESSAGE_TEMPLATE_ID")
GROUP_MESSAGE_TEMPLATE_ID_DE = env("GROUP_MESSAGE_TEMPLATE_ID_DE")
PROJECT_COMMENT_TEMPLATE_ID = env("PROJECT_COMMENT_TEMPLATE_ID")
PROJECT_MENTION_TEMPLATE_ID = env("PROJECT_MENTION_TEMPLATE_ID")
PROJECT_MENTION_TEMPLATE_ID_DE = env("PROJECT_MENTION_TEMPLATE_ID_DE")
PROJECT_COMMENT_TEMPLATE_ID_DE = env("PROJECT_COMMENT_TEMPLATE_ID_DE")
PROJECT_COMMENT_REPLY_TEMPLATE_ID = env("PROJECT_COMMENT_REPLY_TEMPLATE_ID")
PROJECT_COMMENT_REPLY_TEMPLATE_ID_DE = env("PROJECT_COMMENT_REPLY_TEMPLATE_ID_DE")
PROJECT_FOLLOWER_TEMPLATE_ID = env("PROJECT_FOLLOWER_TEMPLATE_ID")
PROJECT_FOLLOWER_TEMPLATE_ID_DE = env("PROJECT_FOLLOWER_TEMPLATE_ID_DE")
PROJECT_LIKE_TEMPLATE_ID = env("PROJECT_LIKE_TEMPLATE_ID")
PROJECT_LIKE_TEMPLATE_ID_DE = env("PROJECT_LIKE_TEMPLATE_ID_DE")
IDEA_COMMENT_TEMPLATE_ID = env("IDEA_COMMENT_TEMPLATE_ID")
IDEA_COMMENT_TEMPLATE_ID_DE = env("IDEA_COMMENT_TEMPLATE_ID_DE")
IDEA_COMMENT_REPLY_TEMPLATE_ID = env("IDEA_COMMENT_REPLY_TEMPLATE_ID")
IDEA_COMMENT_REPLY_TEMPLATE_ID_DE = env("IDEA_COMMENT_REPLY_TEMPLATE_ID_DE")
IDEA_MENTION_TEMPLATE_ID = env("IDEA_MENTION_TEMPLATE_ID")
IDEA_MENTION_TEMPLATE_ID_DE = env("IDEA_MENTION_TEMPLATE_ID_DE")
JOINED_IDEA_TEMPLATE = env("JOINED_IDEA_TEMPLATE")
JOINED_IDEA_TEMPLATE_DE = env("JOINED_IDEA_TEMPLATE_DE")
PROJECT_JOIN_REQUEST_TEMPLATE_ID = env("PROJECT_JOIN_REQUEST_TEMPLATE_ID")
PROJECT_JOIN_REQUEST_TEMPLATE_ID_DE = env("PROJECT_JOIN_REQUEST_TEMPLATE_ID_DE")
ORGANIZATION_FOLLOWER_TEMPLATE_ID = env("ORGANIZATION_FOLLOWER_TEMPLATE_ID")
ORGANIZATION_FOLLOWER_TEMPLATE_ID_DE = env("ORGANIZATION_FOLLOWER_TEMPLATE_ID_DE")
ORG_PUBLISHED_NEW_PROJECT_TEMPLATE_ID = env("ORG_PUBLISHED_NEW_PROJECT_TEMPLATE_ID")
ORG_PUBLISHED_NEW_PROJECT_TEMPLATE_ID_DE = env(
    "ORG_PUBLISHED_NEW_PROJECT_TEMPLATE_ID_DE"
)

FRONTEND_URL = env("FRONTEND_URL", "")
LOCATION_SERVICE_BASE_URL = env("LOCATION_SERVICE_BASE_URL")
ENABLE_LEGACY_LOCATION_FORMAT = env("ENABLE_LEGACY_LOCATION_FORMAT")
DEEPL_API_KEY = env("DEEPL_API_KEY")

ASGI_APPLICATION = "climateconnect_main.routing.application"
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [
                {
                    "address": (env("REDIS_HOST"), env("REDIS_PORT", 6379)),
                    "password": env("REDIS_PASSWORD"),
                    "ssl": True,
                }
            ]
        },
    }
}

# For Celery we use Redis as a broker URL
CELERY_BROKER_URL = env("CELERY_BROKER_URL")
CELERY_RESULT_BACKEND = env("CELERY_BROKER_URL")  # Store results in Redis

if env("ENVIRONMENT") == "production":
    CELERY_BROKER_USE_SSL = {"ssl_cert_reqs": ssl.CERT_REQUIRED}
    CELERY_REDIS_BACKEND_USE_SSL = {"ssl_cert_reqs": ssl.CERT_REQUIRED}

CELERY_TIMEZONE = "UTC"

# Celery performance optimizations
CELERY_WORKER_PREFETCH_MULTIPLIER = 4  # Prefetch 4 tasks per worker
CELERY_TASK_ACKS_LATE = True  # Acknowledge after task completes (prevents task loss)
CELERY_TASK_REJECT_ON_WORKER_LOST = True  # Re-queue if worker dies
CELERY_RESULT_EXPIRES = 3600  # Results expire after 1 hour
CELERY_TASK_COMPRESSION = "gzip"  # Compress task payloads
CELERY_RESULT_COMPRESSION = "gzip"  # Compress results
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
LOCALES = ["en", "de"]

LOCALE_PATHS = [
    BASE_DIR + "/translations",
]


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {"simple": {"format": "{levelname} {message}", "style": "{"}},
    "handlers": {"console": {"level": "INFO", "class": "logging.StreamHandler"}},
    "loggers": {"django": {"handlers": ["console"], "level": "INFO"}},
}

# Setting up cache with optimized Redis configuration
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": env("REDIS_URL"),
        "OPTIONS": {
            "PASSWORD": env("REDIS_PASSWORD"),
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            # Use hiredis for faster Redis parsing (C implementation)
            "PARSER_CLASS": "redis.connection.HiredisParser",
            # Connection pool settings for better performance
            "CONNECTION_POOL_CLASS": "redis.BlockingConnectionPool",
            "CONNECTION_POOL_KWARGS": {
                "max_connections": 50,
                "timeout": 20,
            },
            # Compression for large values (saves bandwidth)
            "COMPRESSOR": "django_redis.compressors.zlib.ZlibCompressor",
            # Ignore cache errors to prevent site downtime
            "IGNORE_EXCEPTIONS": True,
        },
        "KEY_PREFIX": "cc",
        "TIMEOUT": 2 * 24 * 3600,  # 2 days default
    },
    # Separate cache for sessions (longer timeout)
    "sessions": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": env("REDIS_URL"),
        "OPTIONS": {
            "PASSWORD": env("REDIS_PASSWORD"),
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "PARSER_CLASS": "redis.connection.HiredisParser",
        },
        "KEY_PREFIX": "cc_session",
        "TIMEOUT": 7 * 24 * 3600,  # 7 days for sessions
    },
}

# Use Redis for session storage (faster than database)
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "sessions"

DEFAULT_CACHE_TIMEOUT = 2 * 24 * 3600

USER_CHUNK_SIZE = env("USER_CHUNK_SIZE", 100)

CACHE_BACHED_RANK_REQUEST = env("CACHE_BACHED_RANK_REQUEST", "False") == "true"

# SENTRY setup
SENTRY_DSN = env("SENTRY_DSN")
SENTRY_ENVIRONMENT = env("SENTRY_ENVIRONMENT")

sentry_sdk.init(
    dsn=SENTRY_DSN,
    integrations=[DjangoIntegration(), CeleryIntegration(), RedisIntegration()],
    # Set traces_sample_rate to 1.0 to capture 100%
    # of transactions for performance monitoring.
    # We recommend adjusting this value in production,
    traces_sample_rate=1.0,
    # If you wish to associate users to errors (assuming you are using
    # django.contrib.auth) you may enable sending PII data.
    send_default_pii=True,
    # By default the SDK will try to use the SENTRY_RELEASE
    # environment variable, or infer a git commit
    # SHA as release, however you may want to set
    # something more human-readable.
    # release="myapp@1.0.0",
    # SENTRY ENVIRONMENT for local env is "development"
    # and for prod env is "production"
    environment=SENTRY_ENVIRONMENT,
)

CLIMATE_CONNECT_CONTACT_EMAIL = env(
    "CLIMATE_CONNECT_CONTACT_EMAIL", "contact@climateconnect.earth"
)

# Django 3.2+: Default primary key field type for models without explicit primary key
# This prevents warnings and ensures consistent behavior
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# =============================================================================
# PERFORMANCE SETTINGS (Cost-conscious defaults)
# =============================================================================

# Enable cache warming tasks (requires extra Redis memory ~50KB)
# Set to True only if you have Redis headroom and want proactive caching
ENABLE_CACHE_WARMING = env("ENABLE_CACHE_WARMING", "false").lower() == "true"
